### PR TITLE
add r2d2 connection pool

### PR DESCRIPTION
**Pull request by jaredzhou**
it seems like we dont need to clone the Config, we just need to clone the connection for more connections.

### CODE REVIEW

**Comment by wangfenjin** [comment]
You can try to run `cargo clippy --all-targets --workspace --features bundled --features modern-full -- -D warnings -A clippy::redundant-closure` locally to test

**Comment by wangfenjin** [comment]
Also let's make r2d2 as a feature so that anyone doesn't need connection pool don't need to depends on this.

You can refer to what I did for `chrono`, should be several lines of config change

**Comment by jaredzhou** [comment]
> Also let's make r2d2 as a feature so that anyone doesn't need connection pool don't need to depends on this.
> 
> You can refer to what I did for `chrono`, should be several lines of config change

did not see this , i will fix this

**Comment by wangfenjin** [comment]
Thanks for your great work!

Close #6

**Comment by jaredzhou** [comment]
thank u for the patience

**Pull request merged**
